name: build

on:
  - pull_request
  - push

jobs:
  ci:
    uses: php-forge/ci/.github/workflows/phpunit.yml@main
  secrets:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  with:
    os: >-
      [ubuntu-latest, windows-latest]
    php: >-
      [8.0, 8.1]

