name: mutation test

jobs:
  mutation:
    uses: php-forge/reusable-actions/.github/workflows/roave-infection.yml@main
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
